Action()
{

	web_set_sockets_option("SSL_VERSION", "2&3");
 
	lr_start_transaction("1_drill into candidate");

	web_url("manage.aspx", 
		"URL=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Recruiter/", 
		"Snapshot=t190.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Telerik.Web.UI.WebResource.axd?_TSM_HiddenField_=ctl00_ctl00_radScriptManager_TSM&compress=1&_TSM_CombinedScripts_=%3b%3bSystem.Web.Extensions%2c+Version%3d4.0.0.0%2c+Culture%3dneutral%2c+PublicKeyToken%3d31bf3856ad364e35%3aen-US%3a92dc34f5-462f-43bd-99ec-66234f705cd1%3aea597d4b%3ab25378d2%3bTelerik.Web.UI%2c+Version%3d2013.1.220.40%2c+Culture%3dneutral%2c+"
		"PublicKeyToken%3d121fae78165ba3d4%3aen-US%3ad8ebf3de-0179-4fa4-89e6-a030e0cf94a1%3a16e4e7cd%3aed16cbdc%3a874f8ea2%3af7645509%3a24ee1bba%3af46195d3%3a19620875%3a39040b5c%3a6a6d718d%3ae330518b%3a1e771326%3a8e6f0d33%3a7165f74", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Services/UpdateService.asmx/js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZUX9a-bheLFYjLUtFxvckIy1RSNOyJCMttZqx1iQU", "Referer=", ENDITEM, 
		LAST);

	web_custom_request("addrecent", 
		"URL=https://staff.belflex.com/api/bookmark/addrecent", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t191.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={\"abouttypeid\":6,\"referenceid\":2494772,\"name\":\"Kandasamy Java/j2ee Developer (2494772)\",\"userinfo\":\"%7b%22UserID%22%3a%2208b5c73d-8e4d-467c-82be-0c6789f8f6a5%22%2c%22EntityID%22%3a%2200000000-0000-0000-0000-000000000e01%22%2c%22LoggedInAsMode%22%3a1%2c%22TimeZone%22%3a%22Eastern+Standard+Time%22%7d\"}", 
		LAST);

	web_custom_request("GetWidgetWithSession", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t192.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'tags/tags','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"undefined\"}'}", 
		LAST);

	web_custom_request("GetWidget", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t193.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_1, 
		LAST);

	web_custom_request("GetWidget_2", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t194.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_2, 
		LAST);

	web_custom_request("GetWidget_3", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t195.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_3, 
		LAST);

	web_custom_request("GetWidget_4", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t196.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_4, 
		LAST);

	web_custom_request("GetWidget_5", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t197.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_5, 
		LAST);

	web_custom_request("GetWidget_6", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t198.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_6, 
		LAST);

	web_custom_request("GetWidget_7", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t199.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_7, 
		LAST);

	web_custom_request("GetWidgetWithSession_2", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t200.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		body_variable_8, 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/email.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidget_8", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t201.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'contactmethods','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"%7B%20%27Name%27%3A%20%27Kandasamy+Java%252fj2ee+"
		"Developer%27%2C%20%27Email%27%3A%20%27%27%2C%20%27Address%27%3A%20%27eyJDb21tdW5pY2F0aW9uVHlwZSI6NDAwLCJTdGF0ZUNvZGUiOiJHQSIsIlN0YXRlTmFtZSI6Ikdlb3JnaWEiLCJDb3VudHJ5TmFtZSI6IlVuaXRlZCBTdGF0ZXMgb2YgQW1lcmljYSIsIlJlZ2lvbk5hbWUiOiIiLCJDb21tdW5pY2F0aW9uVHlwZUlkIjo0MDAsIk5hbWUiOiJNYWluIEFkZHJlc3MiLCJBZGRyZXNzSUQiOjYyNzI3ODUsIkFkZHJlc3NMaW5lMSI6IiIsIkFkZHJlc3NMaW5lMiI6IiIsIkNpdHkiOiJBbHBoYXJldHRhIiwiU3RhdGVJRCI6MTUsIkNvdW50cnlJRCI6MjIwLCJQb3N0YWxDb2RlIjoiMzAwMDQiLCJSZWdpb25JRCI6bnVsbH0%253d%27%2C%20%27A"
		"ddressID%27%3A%206272785%2C%20%27NrOfAddresses%27%3A%201%20%7D\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/check.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/arrowjoin.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/disk.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/calendar_add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/printer.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/webpage.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/90.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/position.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/note_add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/6.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/task_add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/money.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/key.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/calendar.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/apps/linkedin.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/phone.png", "Referer=https://staff.belflex.com/MVC/Content/css/erecruit.css", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/sms.png", "Referer=https://staff.belflex.com/MVC/Content/css/erecruit.css", ENDITEM, 
		LAST);

	web_custom_request("ManageCandidateAccrualSchedules", 
		"URL=https://staff.belflex.com/MVC/CandidateAccrualSchedule/ManageCandidateAccrualSchedules?candidateID=2494772", 
		"Method=GET", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t202.inf", 
		"Mode=HTML", 
		"EncType=application/x-www-form-urlencoded; charset=utf-8", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/paid.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/App_Themes/Default/javascript/jquery.validate.unobtrusive.js?_=1583878626584", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/8.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/match.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/candidatereference.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/attachment.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/260.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/270.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/3.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/requirements.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/12.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/20.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/80.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/email_ok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/email_nok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/phone_ok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/phone_nok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/sms_ok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/sms_nok.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/info.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/form.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/edit.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/print.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/tax.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("GetWidget_9", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidget", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t203.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'address/address','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\""
		"%7B%20%27Address%27%3A%20%27eyJDb21tdW5pY2F0aW9uVHlwZSI6NDAwLCJTdGF0ZUNvZGUiOiJHQSIsIlN0YXRlTmFtZSI6Ikdlb3JnaWEiLCJDb3VudHJ5TmFtZSI6IlVuaXRlZCBTdGF0ZXMgb2YgQW1lcmljYSIsIlJlZ2lvbk5hbWUiOiIiLCJDb21tdW5pY2F0aW9uVHlwZUlkIjo0MDAsIk5hbWUiOiJNYWluIEFkZHJlc3MiLCJBZGRyZXNzSUQiOjYyNzI3ODUsIkFkZHJlc3NMaW5lMSI6IiIsIkFkZHJlc3NMaW5lMiI6IiIsIkNpdHkiOiJBbHBoYXJldHRhIiwiU3RhdGVJRCI6MTUsIkNvdW50cnlJRCI6MjIwLCJQb3N0YWxDb2RlIjoiMzAwMDQiLCJSZWdpb25JRCI6bnVsbH0%253d%27%2C%20%27AddressID%27%3A%206272785%2C%20%27NrOfAddr"
		"esses%27%3A%201%20%20%20%7D\"}'}", 
		LAST);

	web_custom_request("GetWidgetWithSession_3", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t204.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'communicationlist','data':'{\"AboutType\":\"Candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"%7B%20Mode%3A%20%27Sidebar%27%2C%20%27Email%27%20%3A%20%27%27%2C%20%27FullName%27%20%3A%20%27Kandasamy%20Java%252fj2ee%20Developer%27%20%20%7D\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/positionmatching.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/time.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/7.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/1.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/3.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/communicationtypes/2.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/14/edit.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/profile.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/date.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/OnboardingIntegration/OnboardingMenu.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/RightBarSettings/RightBarSettings.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Base/autobind.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/house.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Controls/Help.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/14/houses.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/14/link.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Base/dataSource.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);
/*
	web_url("OnboardingMenu.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/OnboardingIntegration/Templates/OnboardingMenu.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t205.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/Mvc/Localization/LocalizationModel", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("Help.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Controls/Templates/Help.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t206.inf", 
		"Mode=HTML", 
		LAST);

	web_url("InfoBox.html_3", 
		"URL=https://staff.belflex.com/MVC/Content/js/Controls/Templates/InfoBox.html", 
		"TargetFrame=", 
		"Resource=0", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t207.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/OnboardingIntegration/interfaces.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=../Select.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZxAgcuN_Md9EjLUtFxvckIy1RSNOyJCMttZqx1iQjLZFhlU4kIy2aNWYxJBQ=", "Referer=", ENDITEM, 
		"Url=/MVC/Content/js/BL/Awr/QualifyingPeriodCounter.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Awr/BreakInServiceLog.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/api/onboarding/AllCancellationReasons?OnboardingType=1", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST); */

	web_custom_request("get", 
		"URL=https://staff.belflex.com/Mvc/userSettings/get", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t208.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"RightBar.notes_sectioncontact_sectionrelated_sectionactions_sectionother_section\",\"ContainerID\":\"RightBar.SectionsOrder\"}", 
		LAST);

	web_url("QualifyingPeriodCounter.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Awr/Templates/QualifyingPeriodCounter.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t209.inf", 
		"Mode=HTML", 
		LAST);

	web_url("BreakInServiceLog.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Awr/Templates/BreakInServiceLog.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t210.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/Tags/TagsView.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_custom_request("get_2", 
		"URL=https://staff.belflex.com/Mvc/userSettings/get", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t211.inf", 
		"Mode=HTML", 
		"EncType=application/json", 
		"Body={\"BucketPath\":\"RightBar.notes_sectioncontact_sectionrelated_sectionactions_sectionother_section\",\"ContainerID\":\"RightBar.CollapsedSections\"}", 
		EXTRARES, 
		"Url=/MVC/Content/js/BL/Candidate/CandidateReview.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("TagsView.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagsView.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t212.inf", 
		"Mode=HTML", 
		LAST);

	web_url("TagsGridCell.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagsGridCell.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t213.inf", 
		"Mode=HTML", 
		LAST);

	web_url("CandidateReviewsList.html", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Candidate/Templates/CandidateReviewsList.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t214.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Search/EmbeddedSearch.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Awr/Events.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Tags/common.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/BL/Tags/TagView.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/External/Knockout/knockout.mapping-latest.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/js/Currency/CurrencyService.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("TagView.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/BL/Tags/Templates/TagView.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t215.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/Values/Types/CLR/numericType.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Currency/CurrencyModel", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/currency/forLookup-all", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/delete.png", "Referer=https://staff.belflex.com/MVC/Content/css/erecruit.css", ENDITEM, 
		"Url=/MVC/Content/js/Search/SearchResults.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/CandidateReview/GetByCandidateId/?id=2494772", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("SearchResults.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Templates/SearchResults.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t216.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=../LiveFilterService.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=../Criterion.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("Criterion.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Templates/Criterion.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t217.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/MVC/Content/js/External/Kendo/js-debug/kendo.web.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Search/Awr/By/QualifyingPeriodCounter?candidateID=2494772", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Search/Awr/By/BreakInService?candidateID=2494772", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		//"Url=https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZdoWWL7uC1nMjLUtFxvckIy2UkJL6JCMtUUjTsiQjLbWasdYkIy2RYZVOJCMtmjVmMSQU", "Referer=", ENDITEM, 
		//"Url=https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZMjw816btDJ0jLUtFxvckIy2UkJL6JCMtlJCS-iQjLVFI07IkIy21mrHWJCMtkWGVTiQjLZo1ZjEkFA==", "Referer=", ENDITEM, 
		"Url=../Components/Columns.js", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	web_url("Columns.html_2", 
		"URL=https://staff.belflex.com/MVC/Content/js/Search/Components/Templates/Columns.html", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t218.inf", 
		"Mode=HTML", 
		EXTRARES, 
		"Url=/mvc/dispatch/ping?connectionData=%5B%7B%22name%22%3A%22notification%22%7D%5D&_=1583878361347", "Referer=https://staff.belflex.com/Recruiter/", ENDITEM, 
		LAST);

	lr_end_transaction("1_drill into candidate",LR_AUTO);

	lr_start_transaction("1_click on add attachment");
	
    web_reg_find("Text=Add an attachment", LAST);

	web_custom_request("GetWidgetWithSession_4", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t219.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'attachment/new','data':'{\"AboutType\":\"candidate\",\"ReferenceID\":2494772,\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"%7B%20%27CallerID%27%20%3A%20%27RecordCounts_Candidate_2494772%27%2C%20%27FromFile%27%3A%20%27%27%20%7D\"}'}", 
		EXTRARES, 
		"Url=https://clients1.google.com/tbproxy/af/query?q=Chc2LjEuMTcxNS4xNDQyL2VuIChHR0xMKRMZ8j1O2qQhTdAjLRtwfsskIy34RsfoJCMtrD1FWyQjLSCxblMkIy144NEnJBQ=", "Referer=", ENDITEM, 
		"Url=/MVC/Content/images/bits/jqueryui/ui-icons_888888_256x240.png", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/paste_word.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/add.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/images/icons/calendar.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/images/ajaxloader_small.gif", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/attachment_hr.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/images/bits/jqueryui/ui-bg_glass_75_dadada_1x400.png", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		LAST);

	lr_end_transaction("1_click on add attachment",LR_AUTO);

	lr_start_transaction("1_select type");

	web_custom_request("GetWidgetWithSession_5", 
		"URL=https://staff.belflex.com/Services/CoolTipService.asmx/GetWidgetWithSession", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t220.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={'widgetname':'sharingoptionmanager','data':'{\"LoggedInAsMode\":\"Recruiter\",\"CurrentUserID\":\"08b5c73d-8e4d-467c-82be-0c6789f8f6a5\",\"CurrentEntityID\":\"00000000-0000-0000-0000-000000000e01\",\"AdditionalData\":\"%7B%20%27DefaultOptions%27%3A%20%271%27%2C%20%27LocalVariable%27%3A%27widget_new_712994_ShareOptions%27%20%7D\"}'}", 
		EXTRARES, 
		"Url=/Mvc/Content/Images/icons/abouttypes/31.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/7.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/abouttypes/2.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		LAST);

	lr_end_transaction("1_select type",LR_AUTO);

	lr_start_transaction("1_add file");

	web_reg_save_param("AttachmentID", "LB=\"AttachmentID\":\"", "RB=\"", LAST);
	
	web_custom_request("upload", 
		"URL=https://staff.belflex.com/api/attachment/upload?qqfile=attachment.png", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=text/plain", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t221.inf", 
		"Mode=HTML", 
		"EncType=application/octet-stream", 
		body_variable_9, 
		EXTRARES, 
		"Url=/Mvc/Content/Images/loading.gif", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/Mvc/Content/Images/icons/filetypes/png.png", "Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", ENDITEM, 
		"Url=/MVC/Content/images/bits/jqueryui/ui-icons_454545_256x240.png", "Referer=https://staff.belflex.com/MVC/Content/css/Library/library.min.css", ENDITEM, 
		LAST);

	lr_end_transaction("1_add file",LR_AUTO);

	lr_start_transaction("1_click submit");

		web_reg_find("Text={\"Messages\":[],\"Success\":true,\"success\":true,\"Result\"", 
		LAST);
		web_custom_request("add", 
		"URL=https://staff.belflex.com/api/attachment/add", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t222.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={\"data\":{\"AboutTypeID\":6,\"ReferenceID\":2494772,\"AttachmentID\":\"{AttachmentID}\",\"FileName\":\"\\\\\\\\BELFXP-BE01\\\\Media\\\\Attachments\\\\Temp\\\\{AttachmentID}.png\",\"Name\":\"Application\",\"Note\":\"\",\"TypeID\":\"1002\",\"ExpirationDate\":null,\"ParseSkills\":true,\"MakeDefault\":true,\"UpdateContactInfo\":false,\"ReplaceSkills\":false,\"SharingOptionFlag\":1,\"ParseEducation\":true,\"ReplaceEducation\":false,\"ParseWorkHistory\":true,"
		"\"ReplaceWorkHistory\":false,\"ExternalId\":null},\"UserInfo\":\"%7b%22UserID%22%3a%2208b5c73d-8e4d-467c-82be-0c6789f8f6a5%22%2c%22EntityID%22%3a%2200000000-0000-0000-0000-000000000e01%22%2c%22LoggedInAsMode%22%3a1%2c%22TimeZone%22%3a%22Eastern+Standard+Time%22%7d\"}", 
		LAST);
	
	web_custom_request("add", 
		"URL=https://staff.belflex.com/api/attachment/add", 
		"Method=POST", 
		"TargetFrame=", 
		"Resource=0", 
		"RecContentType=application/json", 
		"Referer=https://staff.belflex.com/Pages/candidate/manage.aspx?refid=2494772&null", 
		"Snapshot=t222.inf", 
		"Mode=HTML", 
		"EncType=application/json; charset=UTF-8", 
		"Body={\"data\":{\"AboutTypeID\":6,\"ReferenceID\":2494772,\"AttachmentID\":\"{AttachmentID}\",\"FileName\":\"%5C%5CBELFXP-BE01%5CMedia%5CAttachments%5CTemp%{AttachmentID}.png\",\"Name\":\"Application\",\"Note\":\"\",\"TypeID\":\"1002\",\"ExpirationDate\":null,\"ParseSkills\":true,\"MakeDefault\":true,\"UpdateContactInfo\":false,\"ReplaceSkills\":false,\"SharingOptionFlag\":1,\"ParseEducation\":true,\"ReplaceEducation\":false,\"ParseWorkHistory\":true,"
		"\"ReplaceWorkHistory\":false,\"ExternalId\":null},\"UserInfo\":\"%7b%22UserID%22%3a%2208b5c73d-8e4d-467c-82be-0c6789f8f6a5%22%2c%22EntityID%22%3a%2200000000-0000-0000-0000-000000000e01%22%2c%22LoggedInAsMode%22%3a1%2c%22TimeZone%22%3a%22Eastern+Standard+Time%22%7d\"}", 
		LAST);

	lr_end_transaction("1_click submit",LR_AUTO);

	return 0;
}